// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEnterDataT struct {
	_        structs.HostLayout
	Filename [256]int8
	Flags    uint64
	Count    uint64
}

type bpfSoEvent struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Ppid      uint32
	Uid       uint32
	Comm      [64]int8
	Syscall   [32]int8
	Filename  [256]int8
	_         [4]byte
	Fd        int64
	Flags     uint64
	Ret       int64
	DestIp    uint32
	DestIpv6  [4]uint32
	DestPort  uint16
	SaFamily  uint16
	Count     uint64
	BytesRw   int64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SysEnterClone    *ebpf.ProgramSpec `ebpf:"sys_enter_clone"`
	SysEnterClone3   *ebpf.ProgramSpec `ebpf:"sys_enter_clone3"`
	SysEnterConnect  *ebpf.ProgramSpec `ebpf:"sys_enter_connect"`
	SysEnterExecve   *ebpf.ProgramSpec `ebpf:"sys_enter_execve"`
	SysEnterOpenat   *ebpf.ProgramSpec `ebpf:"sys_enter_openat"`
	SysEnterOpenat2  *ebpf.ProgramSpec `ebpf:"sys_enter_openat2"`
	SysEnterRead     *ebpf.ProgramSpec `ebpf:"sys_enter_read"`
	SysEnterUnlinkat *ebpf.ProgramSpec `ebpf:"sys_enter_unlinkat"`
	SysEnterVfork    *ebpf.ProgramSpec `ebpf:"sys_enter_vfork"`
	SysEnterWrite    *ebpf.ProgramSpec `ebpf:"sys_enter_write"`
	SysExitOpenat    *ebpf.ProgramSpec `ebpf:"sys_exit_openat"`
	SysExitOpenat2   *ebpf.ProgramSpec `ebpf:"sys_exit_openat2"`
	SysExitRead      *ebpf.ProgramSpec `ebpf:"sys_exit_read"`
	SysExitWrite     *ebpf.ProgramSpec `ebpf:"sys_exit_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	EventHeap *ebpf.MapSpec `ebpf:"event_heap"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	OpenData  *ebpf.MapSpec `ebpf:"open_data"`
	ReadData  *ebpf.MapSpec `ebpf:"read_data"`
	WriteData *ebpf.MapSpec `ebpf:"write_data"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"__unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	EventHeap *ebpf.Map `ebpf:"event_heap"`
	Events    *ebpf.Map `ebpf:"events"`
	OpenData  *ebpf.Map `ebpf:"open_data"`
	ReadData  *ebpf.Map `ebpf:"read_data"`
	WriteData *ebpf.Map `ebpf:"write_data"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.EventHeap,
		m.Events,
		m.OpenData,
		m.ReadData,
		m.WriteData,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	Unused *ebpf.Variable `ebpf:"__unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SysEnterClone    *ebpf.Program `ebpf:"sys_enter_clone"`
	SysEnterClone3   *ebpf.Program `ebpf:"sys_enter_clone3"`
	SysEnterConnect  *ebpf.Program `ebpf:"sys_enter_connect"`
	SysEnterExecve   *ebpf.Program `ebpf:"sys_enter_execve"`
	SysEnterOpenat   *ebpf.Program `ebpf:"sys_enter_openat"`
	SysEnterOpenat2  *ebpf.Program `ebpf:"sys_enter_openat2"`
	SysEnterRead     *ebpf.Program `ebpf:"sys_enter_read"`
	SysEnterUnlinkat *ebpf.Program `ebpf:"sys_enter_unlinkat"`
	SysEnterVfork    *ebpf.Program `ebpf:"sys_enter_vfork"`
	SysEnterWrite    *ebpf.Program `ebpf:"sys_enter_write"`
	SysExitOpenat    *ebpf.Program `ebpf:"sys_exit_openat"`
	SysExitOpenat2   *ebpf.Program `ebpf:"sys_exit_openat2"`
	SysExitRead      *ebpf.Program `ebpf:"sys_exit_read"`
	SysExitWrite     *ebpf.Program `ebpf:"sys_exit_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SysEnterClone,
		p.SysEnterClone3,
		p.SysEnterConnect,
		p.SysEnterExecve,
		p.SysEnterOpenat,
		p.SysEnterOpenat2,
		p.SysEnterRead,
		p.SysEnterUnlinkat,
		p.SysEnterVfork,
		p.SysEnterWrite,
		p.SysExitOpenat,
		p.SysExitOpenat2,
		p.SysExitRead,
		p.SysExitWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpf.o
var _BpfBytes []byte
